package com.invento.product.util;

public class TestConstants {

	public static final String PRODUCT_ID = "6639dd31e5b7490f597ee80f";
	public static final String  JWT_HEADER = "Authorization";
	public static final String  MOCK_JWT_TOKEN = "eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJJbnZlbnRvIiwic3ViIjoiSldUIFRPS0VOIiwidXNlcm5hbWUiOiJUZXN0IFVzZXIiLCJhdXRob3JpdGllcyI6Ik9JRENfVVNFUixTQ09QRV9vcGVuaWQsU0NPUEVfZW1haWwsUk9MRV9JTlZFTlRPX1JPLFNDT1BFX3Byb2ZpbGUiLCJpYXQiOjE3MjAyMTE2NzEsImV4cCI6MTcyMDI0MTY3MX0.brra-c9lQWWKl4B2zL0LeyZBO9tHUIyFql4QyTWKDBgOZXydVC39C6NFCUQGQnGQ";
	public static final String  INVALID_MOCK_JWT_TOKEN = "eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJJbnZlbnRvIiwic3ViIjoiSldUIFRPS0VOIiwidXNlcm5hbWUiOiJUZXN0IFVzZXIiLCJhdXRob3JpdGllcyI6Ik9JRENfVVNFUixTQ09QRV9vcGVuaWQsU0NPUEVfZW1haWwsUk9MRV9JTlZFTlRPX1JPLFNDT1BFX3Byb2ZpbGUiLCJpYXQiOjE3MjAyMTE2NzEsImV4cCI6MTcyMDI0MTY3MX0.brra-c9lQWWKl4B2zL0LeyZBO9tHUIyFql4QyTWKDBgOZXydVC39C6NFCUQGQnG";
	public static final String BEARER = "Bearer ";
	public static final String SWAGGER_UI = "/swagger-ui/";
}
