spring:
  data:
    mongodb:
      uri: mongodb+srv://sagarsisodiya8:Mclaren%40720s@cluster0.i2obfip.mongodb.net/
      database: invento_db
      
mongodb:
  product:
    collection: product
    searchIndex: default

server:
  port: 8081