spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://test:test%40720s@cluster0.i2obfip.mongodb.net/
      database: invento_test
      
mongodb:
  product:
    searchIndex: test